### ISSUE TITLE
replaceAll("\"", "")って何ですか？

### ISSUE THREAD

**Issue by takezoe** [todokr/code-snip#3]
なんのためにやってるのか謎…。

**Comment by todokr** [comment]
ご指摘ありがとうございます！
取得したStringの前後に`"`が入ってしまうので、良くないやり方と感じつつreplaceAllで取り除いていました。

```
val email = Json.stringify(rs.body \ "email").replaceAll("\"", "")
↓↓
val email = (rs.body \ "email").as[String]
```

上記のように修正したのですが、もっと良い方法がありましたらご教示いただけますと幸いです！よろしくお願いいたします！

**Comment by takezoe** [comment]
上記のやり方でよいと思います。
